#define IDI_ICON0                       100
#define IDI_ICON1                       101
#define IDI_ICON2                       102
#define IDI_ICON3                       103
#define IDI_IMAGE1                      104
#define IDR_MENU1                       105
#define IDR_REGION1                     106
#define IDR_TEXT1                       107
#define IDD_DIALOG1                     300
#define IDD_DIALOG2                     301
#define IDD_DIALOG3                     302
#define IDD_DIALOG4                     303
#define IDD_DIALOG5                     304
#define IDD_DIALOG6                     305
#define IDD_DIALOG7                     306
#define IDD_DIALOG8                     307
#define IDC_STATIC1                     200
#define IDC_BUTTON1                     201
#define IDC_BUTTON2                     202
#define IDC_BUTTON3                     203
#define IDC_BUTTON4                     204
#define IDC_BUTTON5                     205
#define IDC_BUTTON6                     206
#define IDC_EDIT1                       207
#define IDC_EDIT2                       208
#define IDC_EDIT3                       209
#define IDC_EDIT4                       210
#define IDC_EDIT5                       211
#define IDC_EDIT6                       212
#define IDC_EDIT7                       213
#define IDC_EDIT8                       214
#define IDC_SPIN1                       215
#define IDC_SPIN2                       216
#define IDC_SPIN3                       217
#define IDC_LIST1                       218
#define IDC_CHECK1                      219
#define ID_FILE_NEW                     10000
#define ID_FILE_OPEN                    10001
#define ID_FILE_SAVE                    10002
#define ID_FILE_SAVEAS                  10003
#define ID_FILE_EXIT                    IDCANCEL
#define ID_IMAGE_LOAD                   10010
#define ID_IMAGE_INFO                   10011
#define ID_IMAGE_SELECTCOLOR            10012
#define ID_IMAGE_ENTERRGB               10013
#define ID_IMAGE_TOLERANCE              10014
#define ID_IMAGE_BACKCOLOR              10015
#define ID_REGION_HIDE                  10020
#define ID_REGION_SHOWMASK              10021
#define ID_REGION_SHOWTRANS             10022
#define ID_REGION_HORIZONTAL            10023
#define ID_REGION_VERTICAL              10024
#define ID_REGION_VIEWRAWDATA           10025
#define ID_HELP_README                  10030
#define ID_HELP_ABOUT                   10031
