#define LANG_NEUTRAL                          0x0
#define LANG_BULGARIAN                        0x2
#define LANG_CHINESE                          0x4
#define LANG_CROATIAN                         0x1A
#define LANG_CZECH                            0x5
#define LANG_DANISH                           0x6
#define LANG_DUTCH                            0x13
#define LANG_ENGLISH                          0x9
#define LANG_FINNISH                          0x0B
#define LANG_FRENCH                           0x0C
#define LANG_GERMAN                           0x7
#define LANG_GREEK                            0x8
#define LANG_HUNGARIAN                        0x0E
#define LANG_ICELANDIC                        0x0F
#define LANG_ITALIAN                          0x10
#define LANG_JAPANESE                         0x11
#define LANG_KOREAN                           0x12
#define LANG_NORWEGIAN                        0x14
#define LANG_POLISH                           0x15
#define LANG_PORTUGUESE                       0x16
#define LANG_ROMANIAN                         0x18
#define LANG_RUSSIAN                          0x19
#define LANG_SLOVAK                           0x1B
#define LANG_SLOVENIAN                        0x24
#define LANG_SPANISH                          0x0A
#define LANG_SWEDISH                          0x1D
#define LANG_TURKISH                          0x1F
#define SUBLANG_NEUTRAL                       0x0
#define SUBLANG_DEFAULT                       0x1
#define SUBLANG_SYS_DEFAULT                   0x2
#define SUBLANG_CHINESE_TRADITIONAL           0x1
#define SUBLANG_CHINESE_SIMPLIFIED            0x2
#define SUBLANG_CHINESE_HONGKONG              0x3
#define SUBLANG_CHINESE_SINGAPORE             0x4
#define SUBLANG_DUTCH                         0x1
#define SUBLANG_DUTCH_BELGIAN                 0x2
#define SUBLANG_ENGLISH_US                    0x1
#define SUBLANG_ENGLISH_UK                    0x2
#define SUBLANG_ENGLISH_AUS                   0x3
#define SUBLANG_ENGLISH_CAN                   0x4
#define SUBLANG_ENGLISH_NZ                    0x5
#define SUBLANG_ENGLISH_EIRE                  0x6
#define SUBLANG_FRENCH                        0x1
#define SUBLANG_FRENCH_BELGIAN                0x2
#define SUBLANG_FRENCH_CANADIAN               0x3
#define SUBLANG_FRENCH_SWISS                  0x4
#define SUBLANG_GERMAN                        0x1
#define SUBLANG_GERMAN_SWISS                  0x2
#define SUBLANG_GERMAN_AUSTRIAN               0x3
#define SUBLANG_ITALIAN                       0x1
#define SUBLANG_ITALIAN_SWISS                 0x2
#define SUBLANG_NORWEGIAN_BOKMAL              0x1
#define SUBLANG_NORWEGIAN_NYNORSK             0x2
#define SUBLANG_PORTUGUESE                    0x2
#define SUBLANG_PORTUGUESE_BRAZILIAN          0x1
#define SUBLANG_SPANISH                       0x1
#define SUBLANG_SPANISH_MEXICAN               0x2
#define SUBLANG_SPANISH_MODERN                0x3
#define SORT_DEFAULT                          0x0
#define SORT_JAPANESE_XJIS                    0x0
#define SORT_JAPANESE_UNICODE                 0x1
#define SORT_CHINESE_BIG5                     0x0
#define SORT_CHINESE_UNICODE                  0x1
#define SORT_KOREAN_KSC                       0x0
#define SORT_KOREAN_UNICODE                   0x1
