;/{{NO_DEPENDENCIES}}
;/ Microsoft Developer Studio generated include file.
;/ Used by WinErr.Rc
;/
 IDI_ICON1 equ                       100
 IDD_DIALOG1 equ                     101
 IDD_DIALOG2 equ                     102
 IDC_EDIT1 equ                       1000
 IDC_COMBO1 equ                      1001

;/ Next default values for new objects
;/ 
;ifdef APSTUDIO_INVOKED
;ifndef APSTUDIO_READONLY_SYMBOLS
 _APS_3D_CONTROLS equ                     1
 _APS_NEXT_RESOURCE_VALUE equ        103
 _APS_NEXT_COMMAND_VALUE equ         40001
 _APS_NEXT_CONTROL_VALUE equ         1002
 _APS_NEXT_SYMED_VALUE equ           101
;endif
;endif
